import {
  EdgeKind,
  GraphDocument,
  GraphEdge,
  GraphNode,
  ServiceType,
} from "@/lib/graph/schema";
import { azureResourceName, terraformIdentifier } from "./naming";
import { expandImplicits, ExpandedGraph } from "./implicits";
import { topologicalSort, TopoResult } from "./ordering";

export type GeneratorContext = {
  originalDocument: GraphDocument;
  expanded: ExpandedGraph;
  document: GraphDocument;
  nodesById: Map<string, GraphNode>;
  edges: GraphEdge[];
  rgNode: GraphNode | null;
  resourceNames: Map<string, string>;
  identifiers: Map<string, string>;
  topo: TopoResult;
};

export function buildGeneratorContext(document: GraphDocument): GeneratorContext {
  const expanded = expandImplicits(document);
  const expandedDoc = expanded.document;
  const nodesById = new Map(expandedDoc.nodes.map((n) => [n.id, n]));
  const seed = expandedDoc.metadata.name;

  const resourceNames = new Map<string, string>();
  const identifiers = new Map<string, string>();
  const seenIdents = new Set<string>();

  for (const node of expandedDoc.nodes) {
    const name = azureResourceName(node.type, node.resourceName, seed);
    resourceNames.set(node.id, name);
    let ident = terraformIdentifier(node.resourceName);
    let suffix = 1;
    while (seenIdents.has(ident)) {
      ident = `${terraformIdentifier(node.resourceName)}_${suffix++}`;
    }
    seenIdents.add(ident);
    identifiers.set(node.id, ident);
  }

  return {
    originalDocument: document,
    expanded,
    document: expandedDoc,
    nodesById,
    edges: expandedDoc.edges,
    rgNode: expandedDoc.nodes.find((n) => n.type === "resourceGroup") ?? null,
    resourceNames,
    identifiers,
    topo: topologicalSort(expandedDoc),
  };
}

export function outgoingOf(ctx: GeneratorContext, sourceId: string, kind?: EdgeKind): GraphEdge[] {
  return ctx.edges.filter((e) => e.source === sourceId && (!kind || e.kind === kind));
}

export function incomingOf(ctx: GeneratorContext, targetId: string, kind?: EdgeKind): GraphEdge[] {
  return ctx.edges.filter((e) => e.target === targetId && (!kind || e.kind === kind));
}

export function findFirstOfType(ctx: GeneratorContext, type: ServiceType): GraphNode | undefined {
  return ctx.document.nodes.find((n) => n.type === type);
}

export function autoComment(ctx: GeneratorContext, id: string, prefix = "#"): string {
  return ctx.expanded.autoNodeIds.has(id) || ctx.expanded.autoEdgeIds.has(id)
    ? `${prefix} auto-generated by implicit expansion`
    : "";
}
