import { GraphDocument } from "@/lib/graph/schema";
import { GeneratedFile, GeneratorResult } from "./types";
import { buildGeneratorContext } from "./shared/context";
import { getServiceDefinition } from "@/lib/catalogue/services";

function safeId(raw: string): string {
  const cleaned = raw.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(cleaned) ? `n_${cleaned}` : cleaned;
}

const CATEGORY_CLASS: Record<string, string> = {
  scaffold: "classDef scaffold fill:#f6f5ee,stroke:#6b7280,color:#111;",
  network: "classDef network fill:#dbeafe,stroke:#1d4ed8,color:#0b1d56;",
  compute: "classDef compute fill:#dcfce7,stroke:#15803d,color:#052e16;",
  data: "classDef data fill:#fef3c7,stroke:#b45309,color:#451a03;",
  security: "classDef security fill:#fee2e2,stroke:#b91c1c,color:#450a0a;",
  observability: "classDef observability fill:#ede9fe,stroke:#5b21b6,color:#1e1b4b;",
  integration: "classDef integration fill:#cffafe,stroke:#0e7490,color:#083344;",
};

const EDGE_STYLE: Record<string, string> = {
  network: "-.->|net|",
  identity: "==>|identity|",
  data: "-->|data|",
  depends_on: "-->",
  diagnostic: "-.->|diag|",
};

export function generateMermaid(document: GraphDocument): GeneratorResult {
  const ctx = buildGeneratorContext(document);
  if (!ctx.topo.ok) {
    return { ok: false, reason: "cycle detected", cycle: ctx.topo.cycle };
  }
  const lines: string[] = [
    `%% Generated by Bunya. Do not edit by hand.`,
    `%% Document: ${document.metadata.name} (${document.metadata.environment})`,
    `flowchart LR`,
  ];

  const usedCategories = new Set<string>();
  for (const node of ctx.document.nodes) {
    const def = getServiceDefinition(node.type);
    usedCategories.add(def.category);
    const id = safeId(node.id);
    const label = `${def.shortLabel}<br/>${node.name.replace(/\|/g, "/")}`;
    const auto = ctx.expanded.autoNodeIds.has(node.id) ? " (auto)" : "";
    lines.push(`    ${id}["${label}${auto}"]:::${def.category}`);
  }

  for (const edge of ctx.edges) {
    const arrow = EDGE_STYLE[edge.kind] ?? "-->";
    lines.push(`    ${safeId(edge.source)} ${arrow} ${safeId(edge.target)}`);
  }

  for (const c of usedCategories) {
    const style = CATEGORY_CLASS[c];
    if (style) lines.push(`    ${style}`);
  }

  const file: GeneratedFile = {
    path: "architecture.mmd",
    language: "mermaid",
    content: lines.join("\n") + "\n",
  };
  return { ok: true, files: [file] };
}
