import { GraphDocument, GraphNode } from "@/lib/graph/schema";
import { GeneratorContext, buildGeneratorContext, outgoingOf } from "./shared/context";
import { GeneratedFile, GeneratorResult } from "./types";

function header(document: GraphDocument, includeSqlAdmin: boolean): string[] {
  const lines = [
    `<#`,
    `.SYNOPSIS`,
    `    Deploys the ${document.metadata.name} architecture to Azure using the Az module.`,
    `.DESCRIPTION`,
    `    Generated by Bunya. Re-runnable. Honours -WhatIf and -Confirm.`,
    `.PARAMETER ResourceGroupName`,
    `    Resource Group to deploy into. Defaults to the value embedded in the document.`,
    `.PARAMETER Location`,
    `    Azure region. Defaults to ${document.metadata.region}.`,
  ];
  if (includeSqlAdmin) {
    lines.push(
      `.PARAMETER SqlAdminPassword`,
      `    Secure string for the SQL Server admin password.`,
    );
  }
  lines.push(
    `.NOTES`,
    `    Requires Az.Accounts, Az.Resources, Az.Websites, Az.Storage, Az.KeyVault,`,
    `    Az.Sql, Az.CosmosDB, Az.Network, Az.OperationalInsights, Az.ApplicationInsights,`,
    `    Az.ApiManagement, Az.ContainerRegistry, Az.ManagedServiceIdentity.`,
    `#>`,
  );
  return lines;
}

function emitNode(node: GraphNode, ctx: GeneratorContext): string[] {
  const name = ctx.resourceNames.get(node.id)!;
  const region = ctx.document.metadata.region;
  switch (node.type) {
    case "resourceGroup":
      return [
        `# Resource Group ${name}`,
        `$rgParams = @{`,
        `    Name     = '${name}'`,
        `    Location = '${region}'`,
        `    Tag      = @{ environment = '${ctx.document.metadata.environment}'; managed_by = 'bunya' }`,
        `}`,
        `New-AzResourceGroup @rgParams -Force | Out-Null`,
      ];
    case "virtualNetwork":
      return [
        `# Virtual Network ${name}`,
        `$vnetParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = $Location`,
        `    AddressPrefix     = '${(node.properties.addressSpace as string) ?? "10.0.0.0/16"}'`,
        `}`,
        `New-AzVirtualNetwork @vnetParams -Force | Out-Null`,
      ];
    case "subnet": {
      const vnetEdge = outgoingOf(ctx, node.id, "depends_on").find(
        (e) => ctx.nodesById.get(e.target)?.type === "virtualNetwork",
      );
      const vnetName = vnetEdge ? ctx.resourceNames.get(vnetEdge.target)! : "main-vnet";
      return [
        `# Subnet ${name}`,
        `$vnet = Get-AzVirtualNetwork -ResourceGroupName $ResourceGroupName -Name '${vnetName}'`,
        `Add-AzVirtualNetworkSubnetConfig -Name '${name}' -VirtualNetwork $vnet -AddressPrefix '${(node.properties.addressPrefix as string) ?? "10.0.1.0/24"}' -PrivateEndpointNetworkPoliciesFlag '${(node.properties.privateEndpointNetworkPolicies as string) ?? "Disabled"}' | Out-Null`,
        `$vnet | Set-AzVirtualNetwork | Out-Null`,
      ];
    }
    case "networkSecurityGroup":
      return [
        `# Network Security Group ${name}`,
        `$nsgParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = $Location`,
        `}`,
        `New-AzNetworkSecurityGroup @nsgParams -Force | Out-Null`,
      ];
    case "privateEndpoint":
      return [
        `# Private Endpoint ${name}`,
        `# Configure with New-AzPrivateEndpoint after upstream resources exist.`,
        `Write-Information 'Skipping ${name} configure step; see Bunya documentation.' -InformationAction Continue`,
      ];
    case "appServicePlan":
      return [
        `# App Service Plan ${name}`,
        `$planParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = $Location`,
        `    Tier              = '${(node.properties.sku as string)?.startsWith("P") ? "PremiumV3" : "Basic"}'`,
        `    NumberofWorkers   = ${(node.properties.capacity as number) ?? 1}`,
        `    WorkerSize        = '${(node.properties.sku as string) ?? "B1"}'`,
        `    Linux             = $${(node.properties.os as string) === "Linux"}`,
        `}`,
        `New-AzAppServicePlan @planParams -Force | Out-Null`,
      ];
    case "appService": {
      const planEdge = outgoingOf(ctx, node.id, "depends_on").find(
        (e) => ctx.nodesById.get(e.target)?.type === "appServicePlan",
      );
      const planName = planEdge ? ctx.resourceNames.get(planEdge.target)! : "main-plan";
      return [
        `# App Service ${name}`,
        `$appParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = $Location`,
        `    AppServicePlan    = '${planName}'`,
        `}`,
        `New-AzWebApp @appParams | Out-Null`,
        `Set-AzWebApp -ResourceGroupName $ResourceGroupName -Name '${name}' -HttpsOnly $${node.properties.httpsOnly !== false} -AssignIdentity $true | Out-Null`,
      ];
    }
    case "functionApp": {
      const planEdge = outgoingOf(ctx, node.id, "depends_on").find(
        (e) => ctx.nodesById.get(e.target)?.type === "appServicePlan",
      );
      const stEdge = outgoingOf(ctx, node.id, "data").find(
        (e) => ctx.nodesById.get(e.target)?.type === "storageAccount",
      );
      const planName = planEdge ? ctx.resourceNames.get(planEdge.target)! : "main-plan";
      const stName = stEdge ? ctx.resourceNames.get(stEdge.target)! : "mainstorage";
      return [
        `# Function App ${name}`,
        `$fnParams = @{`,
        `    ResourceGroupName     = $ResourceGroupName`,
        `    Name                  = '${name}'`,
        `    Location              = $Location`,
        `    PlanName              = '${planName}'`,
        `    StorageAccountName    = '${stName}'`,
        `    Runtime               = '${(node.properties.runtime as string) ?? "node"}'`,
        `    RuntimeVersion        = '${(node.properties.runtimeVersion as string) ?? "20"}'`,
        `    FunctionsVersion      = '4'`,
        `    IdentityType          = 'SystemAssigned'`,
        `}`,
        `New-AzFunctionApp @fnParams | Out-Null`,
      ];
    }
    case "staticWebApp":
      return [
        `# Static Web App ${name}`,
        `$swaParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = $Location`,
        `    SkuName           = '${(node.properties.sku as string) ?? "Standard"}'`,
        `}`,
        `New-AzStaticWebApp @swaParams | Out-Null`,
      ];
    case "storageAccount":
      return [
        `# Storage Account ${name}`,
        `$stgParams = @{`,
        `    ResourceGroupName     = $ResourceGroupName`,
        `    Name                  = '${name}'`,
        `    Location              = $Location`,
        `    SkuName               = '${(node.properties.sku as string) ?? "Standard_LRS"}'`,
        `    Kind                  = '${(node.properties.kind as string) ?? "StorageV2"}'`,
        `    MinimumTlsVersion     = 'TLS1_${((node.properties.minTlsVersion as string) ?? "1.2").split(".")[1]}'`,
        `    AllowBlobPublicAccess = $${node.properties.allowPublicAccess === true}`,
        `    PublicNetworkAccess   = '${node.properties.allowPublicAccess === true ? "Enabled" : "Disabled"}'`,
        `}`,
        `New-AzStorageAccount @stgParams | Out-Null`,
      ];
    case "sqlDatabase": {
      const adminLogin = (node.properties.adminLogin as string) ?? "bunyaadmin";
      return [
        `# Azure SQL ${name}`,
        `$srvParams = @{`,
        `    ResourceGroupName             = $ResourceGroupName`,
        `    ServerName                    = '${name}-srv'`,
        `    Location                      = $Location`,
        `    SqlAdministratorCredentials   = (New-Object System.Management.Automation.PSCredential('${adminLogin}', $SqlAdminPassword))`,
        `    MinimalTlsVersion             = '1.2'`,
        `    PublicNetworkAccess           = 'Disabled'`,
        `}`,
        `New-AzSqlServer @srvParams | Out-Null`,
        `$dbParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    ServerName        = '${name}-srv'`,
        `    DatabaseName      = '${name}'`,
        `    RequestedServiceObjectiveName = '${(node.properties.sku as string) ?? "S0"}'`,
        `}`,
        `New-AzSqlDatabase @dbParams | Out-Null`,
      ];
    }
    case "cosmosDb":
      return [
        `# Cosmos DB ${name}`,
        `$cosParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = @($Location)`,
        `    DefaultConsistencyLevel = '${(node.properties.consistency as string) ?? "Session"}'`,
        `    EnableFreeTier    = $${node.properties.freeTier === true}`,
        `}`,
        `New-AzCosmosDBAccount @cosParams | Out-Null`,
      ];
    case "keyVault":
      return [
        `# Key Vault ${name}`,
        `$kvParams = @{`,
        `    ResourceGroupName            = $ResourceGroupName`,
        `    VaultName                    = '${name}'`,
        `    Location                     = $Location`,
        `    Sku                          = '${(node.properties.sku as string) ?? "standard"}'`,
        `    EnablePurgeProtection        = $${node.properties.purgeProtection !== false}`,
        `    SoftDeleteRetentionInDays    = ${(node.properties.softDeleteRetentionDays as number) ?? 7}`,
        `    EnableRbacAuthorization      = $${node.properties.rbacAuthorization !== false}`,
        `    PublicNetworkAccess          = '${node.properties.publicNetworkAccess === true ? "Enabled" : "Disabled"}'`,
        `}`,
        `New-AzKeyVault @kvParams | Out-Null`,
      ];
    case "applicationInsights": {
      const wsEdge = outgoingOf(ctx, node.id, "depends_on").find(
        (e) => ctx.nodesById.get(e.target)?.type === "logAnalytics",
      );
      const wsName = wsEdge ? ctx.resourceNames.get(wsEdge.target)! : "main-workspace";
      return [
        `# Application Insights ${name}`,
        `$aiParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = $Location`,
        `    Kind              = 'web'`,
        `    WorkspaceResourceId = (Get-AzOperationalInsightsWorkspace -ResourceGroupName $ResourceGroupName -Name '${wsName}').ResourceId`,
        `}`,
        `New-AzApplicationInsights @aiParams | Out-Null`,
      ];
    }
    case "logAnalytics":
      return [
        `# Log Analytics Workspace ${name}`,
        `$logParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = $Location`,
        `    Sku               = '${(node.properties.sku as string) ?? "PerGB2018"}'`,
        `    RetentionInDays   = ${(node.properties.retentionDays as number) ?? 30}`,
        `}`,
        `New-AzOperationalInsightsWorkspace @logParams -Force | Out-Null`,
      ];
    case "frontDoor":
      return [
        `# Front Door ${name}`,
        `$fdParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    SkuName           = '${(node.properties.sku as string) ?? "Standard_AzureFrontDoor"}'`,
        `}`,
        `New-AzFrontDoorCdnProfile @fdParams | Out-Null`,
      ];
    case "applicationGateway":
      return [
        `# Application Gateway ${name}`,
        `Write-Information 'Application Gateway ${name} requires manual frontend/listener config; see Bunya docs.' -InformationAction Continue`,
      ];
    case "apiManagement":
      return [
        `# API Management ${name}`,
        `$apimParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = $Location`,
        `    Sku               = '${(node.properties.sku as string) ?? "Consumption"}'`,
        `    Organization      = '${(node.properties.publisherName as string) ?? "Bunya"}'`,
        `    AdminEmail        = '${(node.properties.publisherEmail as string) ?? "ops@example.com"}'`,
        `}`,
        `New-AzApiManagement @apimParams | Out-Null`,
      ];
    case "containerRegistry":
      return [
        `# Container Registry ${name}`,
        `$acrParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = $Location`,
        `    Sku               = '${(node.properties.sku as string) ?? "Basic"}'`,
        `    EnableAdminUser   = $${node.properties.adminUserEnabled === true}`,
        `}`,
        `New-AzContainerRegistry @acrParams | Out-Null`,
      ];
    case "userAssignedIdentity":
      return [
        `# User-assigned Managed Identity ${name}`,
        `$umiParams = @{`,
        `    ResourceGroupName = $ResourceGroupName`,
        `    Name              = '${name}'`,
        `    Location          = $Location`,
        `}`,
        `New-AzUserAssignedIdentity @umiParams | Out-Null`,
      ];
  }
}

export function generatePowerShell(document: GraphDocument): GeneratorResult {
  const ctx = buildGeneratorContext(document);
  if (!ctx.topo.ok) {
    return { ok: false, reason: "cycle detected", cycle: ctx.topo.cycle };
  }
  const rg = ctx.rgNode ? ctx.resourceNames.get(ctx.rgNode.id) : document.metadata.resourceGroupName;
  const hasSql = ctx.document.nodes.some((n) => n.type === "sqlDatabase");
  const paramLines = [
    `    [string]$ResourceGroupName = '${rg}',`,
    `    [string]$Location = '${document.metadata.region}'`,
  ];
  if (hasSql) {
    paramLines[paramLines.length - 1] = paramLines[paramLines.length - 1] + ",";
    paramLines.push(`    [Parameter(Mandatory)] [SecureString]$SqlAdminPassword`);
  }
  const lines: string[] = [
    ...header(document, hasSql),
    ``,
    `[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'Medium')]`,
    `param(`,
    ...paramLines,
    `)`,
    ``,
    `Set-StrictMode -Version Latest`,
    `$ErrorActionPreference = 'Stop'`,
    `$InformationPreference = 'Continue'`,
    ``,
    `Write-Information "Bunya deployment for ${document.metadata.name} (${document.metadata.environment})"`,
    `if (-not (Get-AzContext -ErrorAction SilentlyContinue)) {`,
    `    throw 'Run Connect-AzAccount before invoking this script.'`,
    `}`,
    ``,
  ];

  for (const node of ctx.topo.order) {
    const block = emitNode(node, ctx);
    if (!block) continue;
    lines.push(...block, "");
  }

  return {
    ok: true,
    files: [
      {
        path: "Deploy-Infrastructure.ps1",
        language: "powershell",
        content: lines.join("\n"),
      },
    ],
  };
}
