import { GraphDocument } from "@/lib/graph/schema";
import { GeneratedFile, GeneratorResult } from "./types";
import { buildGeneratorContext } from "./shared/context";
import { generateMermaid } from "./mermaid";
import { getServiceDefinition } from "@/lib/catalogue/services";

export function generateReadme(document: GraphDocument): GeneratorResult {
  const ctx = buildGeneratorContext(document);
  if (!ctx.topo.ok) {
    return { ok: false, reason: "cycle detected", cycle: ctx.topo.cycle };
  }

  const grouped = new Map<string, { name: string; resourceName: string; auto: boolean }[]>();
  for (const node of ctx.document.nodes) {
    const def = getServiceDefinition(node.type);
    if (!grouped.has(def.label)) grouped.set(def.label, []);
    grouped.get(def.label)!.push({
      name: node.name,
      resourceName: ctx.resourceNames.get(node.id)!,
      auto: ctx.expanded.autoNodeIds.has(node.id),
    });
  }

  const mermaid = generateMermaid(document);
  const mermaidContent =
    mermaid.ok && mermaid.files[0] ? mermaid.files[0].content : "%% mermaid unavailable";

  const lines: string[] = [
    `# ${document.metadata.name}`,
    ``,
    document.metadata.description ?? `Azure architecture generated by Bunya.`,
    ``,
    `**Region:** ${document.metadata.region}  `,
    `**Environment:** ${document.metadata.environment}  `,
    `**Resource Group:** ${document.metadata.resourceGroupName}`,
    ``,
    `## Architecture`,
    ``,
    "```mermaid",
    mermaidContent.trimEnd(),
    "```",
    ``,
    `## Resources`,
    ``,
  ];

  for (const [label, nodes] of [...grouped.entries()].sort()) {
    lines.push(`### ${label}`);
    for (const n of nodes) {
      lines.push(`- \`${n.resourceName}\`${n.auto ? " _(auto-generated)_" : ""} - ${n.name}`);
    }
    lines.push("");
  }

  lines.push(`## Dependencies`);
  lines.push("");
  if (ctx.edges.length === 0) {
    lines.push(`_None defined._`, "");
  } else {
    for (const edge of ctx.edges) {
      const source = ctx.nodesById.get(edge.source);
      const target = ctx.nodesById.get(edge.target);
      if (!source || !target) continue;
      lines.push(`- ${source.name} **${edge.kind}** ${target.name}`);
    }
    lines.push("");
  }

  lines.push(
    `## Deployment`,
    ``,
    `Bunya emits the same graph in multiple formats. Pick the one that fits your workflow.`,
    ``,
    `### Terraform`,
    "```bash",
    `terraform init`,
    `terraform plan -var environment=${document.metadata.environment}`,
    `terraform apply`,
    "```",
    ``,
    `### Bicep`,
    "```bash",
    `az deployment group create --resource-group ${document.metadata.resourceGroupName} \\`,
    `  --template-file main.bicep --parameters main.parameters.json`,
    "```",
    ``,
    `### ARM JSON`,
    "```bash",
    `az deployment group create --resource-group ${document.metadata.resourceGroupName} \\`,
    `  --template-file azuredeploy.json --parameters azuredeploy.parameters.json`,
    "```",
    ``,
    `### az CLI`,
    "```bash",
    `chmod +x deploy.sh && SQL_ADMIN_PASSWORD=... ./deploy.sh`,
    "```",
    ``,
    `### PowerShell`,
    "```powershell",
    `$pwd = Read-Host -AsSecureString 'SQL admin password'`,
    `Connect-AzAccount`,
    `./Deploy-Infrastructure.ps1 -SqlAdminPassword $pwd -WhatIf`,
    "```",
    ``,
    `---`,
    `Generated by [Bunya](https://github.com/your-org/bunya).`,
  );

  const file: GeneratedFile = {
    path: "README.md",
    language: "markdown",
    content: lines.join("\n"),
  };
  return { ok: true, files: [file] };
}
