import { describe, expect, it } from "vitest";
import { generateTerraform } from "./terraform";
import { firstCutGraph } from "./__fixtures__/firstCut";
import { fullStackGraph } from "./__fixtures__/fullStack";

describe("generateTerraform", () => {
  it("produces a stable file set for the first-cut fixture", () => {
    const result = generateTerraform(firstCutGraph);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const summary = {
      paths: result.files.map((f) => f.path),
      mainTf: result.files.find((f) => f.path === "main.tf")?.content,
      versionsTf: result.files.find((f) => f.path === "versions.tf")?.content,
      outputsTf: result.files.find((f) => f.path === "outputs.tf")?.content,
    };
    expect(summary).toMatchSnapshot();
  });

  it("emits each of the five first-cut Terraform resource types", () => {
    const result = generateTerraform(firstCutGraph);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const main = result.files.find((f) => f.path === "main.tf")?.content ?? "";
    for (const kind of [
      "azurerm_resource_group",
      "azurerm_service_plan",
      "azurerm_linux_web_app",
      "azurerm_storage_account",
      "azurerm_key_vault",
    ]) {
      expect(main).toContain(kind);
    }
  });

  it("is deterministic across repeated calls", () => {
    const a = generateTerraform(firstCutGraph);
    const b = generateTerraform(firstCutGraph);
    expect(JSON.stringify(a)).toEqual(JSON.stringify(b));
  });

  it("covers every Terraform resource for the full-stack fixture", () => {
    const result = generateTerraform(fullStackGraph);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const main = result.files.find((f) => f.path === "main.tf")?.content ?? "";
    for (const kind of [
      "azurerm_resource_group",
      "azurerm_virtual_network",
      "azurerm_subnet",
      "azurerm_network_security_group",
      "azurerm_private_endpoint",
      "azurerm_service_plan",
      "azurerm_linux_web_app",
      "azurerm_linux_function_app",
      "azurerm_static_web_app",
      "azurerm_storage_account",
      "azurerm_mssql_database",
      "azurerm_cosmosdb_account",
      "azurerm_key_vault",
      "azurerm_application_insights",
      "azurerm_log_analytics_workspace",
      "azurerm_cdn_frontdoor_profile",
      "azurerm_application_gateway",
      "azurerm_api_management",
      "azurerm_container_registry",
      "azurerm_user_assigned_identity",
      "azurerm_monitor_diagnostic_setting",
    ]) {
      expect(main).toContain(kind);
    }
  });

  it("marks auto-generated resources with the implicit comment", () => {
    const minimal = {
      ...firstCutGraph,
      nodes: firstCutGraph.nodes.filter((n) => n.type === "functionApp" || n.type === "appService"),
      edges: [],
    };
    const fn = {
      id: "fn-1",
      type: "functionApp" as const,
      name: "Worker",
      resourceName: "fn-impl-demo",
      position: { x: 0, y: 0 },
      properties: {},
    };
    const result = generateTerraform({ ...minimal, nodes: [fn] });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const main = result.files.find((f) => f.path === "main.tf")?.content ?? "";
    expect(main).toContain("auto-generated by implicit expansion");
    expect(main).toContain("azurerm_storage_account");
  });

  it("refuses to generate when a dependency cycle exists", () => {
    const cyclic = {
      ...firstCutGraph,
      edges: [
        ...firstCutGraph.edges,
        { id: "cycle", source: "kv", target: "app", kind: "depends_on" as const },
      ],
    };
    const result = generateTerraform(cyclic);
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.cycle?.length ?? 0).toBeGreaterThan(0);
  });
});
